### ISSUE TITLE
VOXCONVERT: Layer DNA

### ISSUE THREAD

**Issue by vizuu3d** [mgerhardy/engine#101]
when i run my layer combination to generate the colections the numbers are different than when i generate trought magicavoxel, let me explain:

when i create the collection it makes DNA like that
 - body 1 = 1
- body 2 = 2

- hat 1 = 1
- hat 2 = 2

- eye 1 = 1
- eye 2 = 2

the dna look like that: 1,1,1 
if its layred in magicavoxel it would be: 1,3,5

is there a way to do a simple math to compensate that?
Ex: how many Traits 1 layer have? ___ and them add it into Trait 2 numbers...

**Comment by mgerhardy** [comment]
This might be a duplicate of this ticket: https://github.com/mgerhardy/engine/issues/68

**Comment by mgerhardy** [comment]
Closing this ticket - linked with the other one for the details. Duplicate.
