### ISSUE TITLE
VOXELRENDER: view_distance increase crashes

### ISSUE THREAD

**Issue by geotyper** [mgerhardy/engine#14]
module voxelrender
in  WorldRenderer.cpp

```
WorldRenderer::WorldRenderer(const voxelworld::WorldMgrPtr& world) :
                _octree(math::AABB<int>(), 5), _world(world) {
        setViewDistance(240.0f);
}
```
if increase     setViewDistance to 500 or above / engine crashed

**Comment by mgerhardy** [comment]
I can't reproduce this - though it gets obvious that there is a problem with 500 and up. Looks like it's threading related. Will investigate more.

**Comment by mgerhardy** [comment]
This is not reproducible for me. Closing for now. If you still encounter issues with this one, please reopen with details.
