### ISSUE TITLE
Standalone shadertool

### ISSUE THREAD

**Issue by steadysupply** [mgerhardy/engine#2]
Hello @mgerhardy,

I'm interested in the [shadertool](https://github.com/mgerhardy/engine/tree/master/src/tools/shadertool) you wrote about in your [blog post](http://mgerhardy.blogspot.co.uk/2017/02/cglsl-code-generator.html). It looks really useful as way to have the compiler help with the work of maintaining shaders. I notice there are some dependencies to internal code; are there too many dependencies to make it worthwhile splitting this into a standalone tool?

Greets,

Ben

**Comment by mgerhardy** [comment]
It would need some additional work to extract the engine-specific parts from [Generator.cpp](https://github.com/mgerhardy/engine/blob/master/src/tools/shadertool/Generator.cpp). This is mainly about the render driver stuff. The other parts are just about io and string handling. Should be quite easy.

**Comment by steadysupply** [comment]
> the engine-specific parts

Yes, I see usage of eg.`video::DataType::Float` from [`video/Types.h`](https://github.com/mgerhardy/engine/blob/master/src/modules/video/Types.h) and obviously the `Shader` class from [`video/Shader.h`](https://github.com/mgerhardy/engine/blob/master/src/modules/video/Shader.h). Are there others you were referring to?

**Comment by mgerhardy** [comment]
video::Renderer.h for uploading uniform and attributes. And maybe other. But those are just wrappers around the real gl functions.

**Comment by mgerhardy** [comment]
`video::UniformBuffer` is also a relatively small class that is needed.

**Comment by mgerhardy** [comment]
It might be worth to check out @floooh's [sokol-gfx](https://github.com/floooh/sokol) and the related [shader generator](https://github.com/pjako/shd).

**Comment by steadysupply** [comment]
I've been reading about fips and Oryol these last few days, thanks for the link. Looks great!

:+1:
