### ISSUE TITLE
BACKEND: user name and password auth broken

### ISSUE THREAD

**Issue by geotyper** [mgerhardy/engine#7]
![image](https://user-images.githubusercontent.com/30755433/68859742-017fd680-06f9-11ea-9be2-d9d19270e169.png)
![image](https://user-images.githubusercontent.com/30755433/68859776-152b3d00-06f9-11ea-8e47-232f775df50f.png)
![image](https://user-images.githubusercontent.com/30755433/68860132-eeb9d180-06f9-11ea-9792-16c65880804a.png)

Cant login to server
new account didnt help
Today download your project/ all work for the first look, but client couldnt login to server

**Comment by geotyper** [comment]
> ![image](https://user-images.githubusercontent.com/30755433/68859742-017fd680-06f9-11ea-9be2-d9d19270e169.png)
> ![image](https://user-images.githubusercontent.com/30755433/68859776-152b3d00-06f9-11ea-8e47-232f775df50f.png)
> ![image](https://user-images.githubusercontent.com/30755433/68860132-eeb9d180-06f9-11ea-9792-16c65880804a.png)
> 
> Cant login to server
> new account didnt help
> Today download your project/ all work for the first look, but client couldnt login to server

![image](https://user-images.githubusercontent.com/30755433/68862255-30e51200-06fe-11ea-961c-5b38ba7a1d0c.png)
manually add  user to db/ but don't help

**Comment by geotyper** [comment]
do you have some idea how avoid password authentication? 
server have command to list users from db?

**Comment by mgerhardy** [comment]
You can't avoid it atm. But I can add a server command to register a new user if that would help.

There is currently no command to list all users.

Btw. keep in mind that the game is not yet in a playable state. Help is welcome of course ;)

**Comment by mgerhardy** [comment]
I know what's broken. Will fix it in a few hours. Thanks a lot for the report.

**Comment by mgerhardy** [comment]
You can create a new user from the server console via `sv_createuser my@email.de somename mypasswd`

The auth should be fixed now in the linked revision.

**Comment by geotyper** [comment]
> sv_createuser my@email.de somename

Thanks manual create user from server console works. I can login and looks on world from one point/ but than 
![image](https://user-images.githubusercontent.com/30755433/68929821-2417fb00-079e-11ea-827e-560e4d71f17f.png)
looks like problems with local db.

**Comment by mgerhardy** [comment]
The connection pool has an error. I'm currently working on the mapview tool and the voxedit tool. The client/server stuff might contain a lot of smaller issues. Currently the client doesn't even render the work right. Should only be minor issues, too - as the client is using the same classes as the mapview tool.
But expect to see more error if you try further with client/server (which is a good thing - please report the bugs)
