### ISSUE TITLE
VOXCONVERT: Set bounding box/volume for VXM file via command line

### ISSUE THREAD

**Issue by sthewissen** [mgerhardy/engine#82]
As mentioned in #81 it would be cool if there is a possibility to change the bounding box of a VXM file (incl. for bulk operations). It is stored in the first few bytes of the VXM file, but adjusting them also requires moving around geometry as the file seems to use an indexed format of where geometry sits.

**Comment by mgerhardy** [comment]
That would be a parameter like `--resize x:y:z` for `voxconvert`.

**Comment by mgerhardy** [comment]
implemented with e3cdd11697ea27e5ccb1dc05eb0f2ecc425138db
